Tmerlier/fix no file
etalab/cadastre-bundler-api pull request #5
Opened 2017-12-11 14:39 UTC by tmerlier

2017-12-12 19:04 UTC, jdesboeufs requested changes

2017-12-12 19:04 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +  req.attachmentName = `cadastre-${codeDepartement}-${layer}.json`
Je préfère deux template strings distincts.

2017-12-12 19:04 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +    }
else

2017-12-12 19:04 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +    if (req.sendFile) {
Pas assez explicite, `req.withGzipHeader`

2017-12-12 19:04 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +  req.sendFile = format === 'geojson' && forceDownload
withGzipHeader

2017-12-12 19:04 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +  req.sendFile = format === 'geojson' && forceDownload
withGzipHeader

2017-12-12 19:04 UTC, jdesboeufs commented on lib/fs/pci.js
> +      const regex = this.format === 'tiff' ?
Cette logique doit rester dans le module `fs/pci`

2017-12-12 19:04 UTC, jdesboeufs commented on lib/pci-vecteur.js
> +app.get('/feuilles/:codeFeuille/edigeo-cc', async (req, res) => {
Utiliser `asExpressCallback`

2017-12-12 19:04 UTC, jdesboeufs commented on lib/pci-vecteur.js
> +app.get('/communes/:codeCommune/edigeo-cc', async (req, res) => {
asExpressCallback

2017-12-12 19:04 UTC, jdesboeufs commented on lib/pci-vecteur.js
> +app.get('/communes/:codeCommune/:format', async (req, res) => {
asExpressCallback

2017-12-13 09:26 UTC, tmerlier commented on lib/fs/pci.js
> +      const regex = this.format === 'tiff' ?
C'est le cas non ?

2017-12-13 09:28 UTC, jdesboeufs commented on lib/fs/pci.js
> +      const regex = this.format === 'tiff' ?
Oops pardon :)

2017-12-13 09:48 UTC, tmerlier commented
Good pour toi @jdesboeufs ?

2017-12-13 10:10 UTC, jdesboeufs requested changes

2017-12-13 10:10 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +      res.withGzipHeader(req.bundlePath, {headers: geojsonGzipHeaders})
????

2017-12-13 10:11 UTC, jdesboeufs requested changes

2017-12-13 10:11 UTC, jdesboeufs commented on lib/cadastre-etalab.js
> +      res.withGzipHeader(req.bundlePath, {headers: geojsonGzipHeaders})
Ça n'existe pas

2017-12-13 10:45 UTC, tmerlier commented on lib/cadastre-etalab.js
> +      res.withGzipHeader(req.bundlePath, {headers: geojsonGzipHeaders})
-_-'… C'est ça de faire des "replace all"

2017-12-13 11:16 UTC, jdesboeufs approved these changes

2017-12-13 11:17 UTC, merged